#ifndef COMPILER_CONTEXT_METACOMMANDS_H
#define COMPILER_CONTEXT_METACOMMANDS_H

#include <fm/common.hpp>

// TRACK META INFO
#define SHEET_META__INSTRUMENT FM_STRING("instrument")
#define SHEET_META__TRACK_META_KEY_TYPE FM_STRING("type")
#define SHEET_META__TRACK_META_VALUE_TYPE_STYLE FM_STRING("style")
#define SHEET_META__TRACK_META_VALUE_TYPE_SHEET FM_STRING("sheet")
#define SHEET_META__TRACK_META_KEY_PART FM_STRING("part")
#define SHEET_META__TRACK_META_KEY_NAME FM_STRING("name")


// VOICE
#define SHEET_META__MIDI_INSTRUMENT_DEF FM_STRING("instrumentDef")
#define SHEET_META__MIDI_CHANNEL FM_STRING("channel")
#define SHEET_META__MIDI_SOUNDSELECT FM_STRING("soundSelect")
#define SHEET_META__SET_STYLE FM_STRING("style")
#define SHEET_META__SET_VOLUME FM_STRING("volume")
#define SHEET_META__SET_PAN FM_STRING("pan")
#define SHEET_META__SET_INSTRUMENT_CONFIG FM_STRING("instrumentConf")
#define SHEET_META__SET_INSTRUMENT_CONFIG_VOLUME FM_STRING("volume")
#define SHEET_META__SET_INSTRUMENT_CONFIG_PAN FM_STRING("pan")
#define SHEET_META__SET_SINGLE_EXPRESSION FM_STRING("singleExpression")
#define SHEET_META__SET_EXPRESSION FM_STRING("expression")
#define SHEET_META__SET_TEMPO FM_STRING("tempo")
#define SHEET_META__SET_UPBEAT FM_STRING("upbeat")
#define SHEET_META__SET_VOICING_STRATEGY FM_STRING("voicingStrategy")
#define SHEET_META__SET_SPIELANWEISUNG FM_STRING("do")
#define SHEET_META__SET_SPIELANWEISUNG_ONCE FM_STRING("doOnce")
#define SHEET_META__SET_MOD FM_STRING("mod")
#define SHEET_META__SET_MOD_ONCE FM_STRING("modOnce")
#define SHEET_META__SET_SIGNATURE FM_STRING("signature")
#define SHEET_META__SET_DEVICE FM_STRING("device")
#define SHEET_META__SET_VORSCHLAG FM_STRING("vorschlag")

#endif