#ifndef COMPILER_CONTEXT_METACOMMANDS_H
#define COMPILER_CONTEXT_METACOMMANDS_H

#include <fm/common.hpp>

#define SHEET_META__MIDI_INSTRUMENT_DEF FM_STRING("instrument")
#define SHEET_META__MIDI_CHANNEL FM_STRING("channel")
#define SHEET_META__MIDI_SOUNDSELECT FM_STRING("soundSelect")
#define SHEET_META__SET_UNAME FM_STRING("uname")
#define SHEET_META__SET_STYLE FM_STRING("style")
#define SHEET_META__SET_SINGLE_EXPRESSION FM_STRING("singleExpression")
#define SHEET_META__SET_EXPRESSION FM_STRING("expression")
#define SHEET_META__SET_TEMPO FM_STRING("tempo")
#define SHEET_META__SET_UPBEAT FM_STRING("upbeat")
#define SHEET_META__SET_VOICING_STRATEGY FM_STRING("voicingStrategy")
#define SHEET_META__SET_SPIELANWEISUNG FM_STRING("do")
#define SHEET_META__SET_SPIELANWEISUNG_ONCE FM_STRING("doOnce")
#define SHEET_META__SET_MOD FM_STRING("mod")
#define SHEET_META__SET_MOD_ONCE FM_STRING("modOnce")

#endif