#ifndef COMPILER_VOICING_SRATEGIES_H
#define COMPILER_VOICING_SRATEGIES_H

#include <fm/common.hpp>
#define SHEET_VOICING_STRATEGY_SIMPLE_GUITAR FM_STRING("simpleGuitar")
#define SHEET_VOICING_STRATEGY_AS_NOTATED FM_STRING("asNotated")
#define SHEET_VOICING_STRATEGY_DEFAULT SHEET_VOICING_STRATEGY_AS_NOTATED
#endif