#include "GmInstrumentNames.h"

namespace com
{
    const GmInstruments gmInstruments({
        {"Acoustic Grand Piano", 0},
        {"Bright Acoustic Piano", 1},
        {"Electric Grand Piano", 2},
        {"Honky-tonk Piano", 3},
        {"Electric Piano 1", 4},
        {"Electric Piano 2", 5},
        {"Harpsichord", 6},
        {"Clavi", 7},
        {"Celesta", 8},
        {"Glockenspiel", 9},
        {"Music Box", 10},
        {"Vibraphone", 11},
        {"Marimba", 12},
        {"Xylophone", 13},
        {"Tubular Bells", 14},
        {"Dulcimer", 15},
        {"Drawbar Organ", 16},
        {"Percussive Organ", 17},
        {"Rock Organ", 18},
        {"Church Organ", 19},
        {"Reed Organ", 20},
        {"Accordion", 21},
        {"Harmonica", 22},
        {"Tango Accordion", 23},
        {"Acoustic Guitar Nylon", 24},
        {"Acoustic Guitar Steel", 25},
        {"Electric Guitar Jazz", 26},
        {"Electric Guitar Clean", 27},
        {"Electric Guitar Muted", 28},
        {"Overdriven Guitar", 29},
        {"Distortion Guitar", 30},
        {"Guitar harmonics", 31},
        {"Acoustic Bass", 32},
        {"Electric Bass Finger", 33},
        {"Electric Bass Pick", 34},
        {"Fretless Bass", 35},
        {"Slap Bass 1", 36},
        {"Slap Bass 2", 37},
        {"Synth Bass 1", 38},
        {"Synth Bass 2", 39},
        {"Violin", 40},
        {"Viola", 41},
        {"Cello", 42},
        {"Contrabass", 43},
        {"Tremolo Strings", 44},
        {"Pizzicato Strings", 45},
        {"Orchestral Harp", 46},
        {"Timpani", 47},
        {"String Ensemble 1", 48},
        {"String Ensemble 2", 49},
        {"SynthStrings 1", 50},
        {"SynthStrings 2", 51},
        {"Choir Aahs", 52},
        {"Voice Oohs", 53},
        {"Synth Voice", 54},
        {"Orchestra Hit", 55},
        {"Trumpet", 56},
        {"Trombone", 57},
        {"Tuba", 58},
        {"Muted Trumpet", 59},
        {"French Horn", 60},
        {"Brass Section", 61},
        {"SynthBrass 1", 62},
        {"SynthBrass 2", 63},
        {"Soprano Sax", 64},
        {"Alto Sax", 65},
        {"Tenor Sax", 66},
        {"Baritone Sax", 67},
        {"Oboe", 68},
        {"English Horn", 69},
        {"Bassoon", 70},
        {"Clarinet", 71},
        {"Piccolo", 72},
        {"Flute", 73},
        {"Recorder", 74},
        {"Pan Flute", 75},
        {"Blown Bottle", 76},
        {"Shakuhachi", 77},
        {"Whistle", 78},
        {"Ocarina", 79},
        {"Lead 1 Square", 80},
        {"Lead 2 Sawtooth", 81},
        {"Lead 3 Calliope", 82},
        {"Lead 4 Chiff", 83},
        {"Lead 5 Charang", 84},
        {"Lead 6 Voice", 85},
        {"Lead 7 Fifths", 86},
        {"Lead 8 Bass+Lead", 87},
        {"Pad 1 New Age", 88},
        {"Pad 2 Warm", 89},
        {"Pad 3 Polysynth", 90},
        {"Pad 4 Choir", 91},
        {"Pad 5 Bowed", 92},
        {"Pad 6 Metallic", 93},
        {"Pad 7 Halo", 94},
        {"Pad 8 Sweep", 95},
        {"FX 1 Rain", 96},
        {"FX 2 Soundtrack", 97},
        {"FX 3 Crystal", 98},
        {"FX 4 Atmosphere", 99},
        {"FX 5 Brightness", 100},
        {"FX 6 Goblins", 101},
        {"FX 7 Echoes", 102},
        {"FX 8 Sci-Fi", 103},
        {"Sitar", 104},
        {"Banjo", 105},
        {"Shamisen", 106},
        {"Koto", 107},
        {"Kalimba", 108},
        {"Bag pipe", 109},
        {"Fiddle", 110},
        {"Shanai", 111},
        {"Tinkle Bell", 112},
        {"Agogo", 113},
        {"Steel Drums", 114},
        {"Woodblock", 115},
        {"Taiko Drum", 116},
        {"Melodic Tom", 117},
        {"Synth Drum", 118},
        {"Reverse Cymbal", 119},
        {"Guitar Fret Noise", 120},
        {"Breath Noise", 121},
        {"Seashore", 122},
        {"Bird Tweet", 123},
        {"Telephone Ring", 124},
        {"Helicopter", 125},
        {"Applause", 126},
        {"Gunshot", 127}
    });
}