#pragma once

#include <com/common.hpp>

// selectors
#define SHEET_CONDUCTOR_SEL__FROM_POSITION FM_STRING("fromPosition")
#define SHEET_CONDUCTOR_SEL__TO_POSITION FM_STRING("toPosition")
#define SHEET_CONDUCTOR_SEL__ON_BEAT FM_STRING("onBeat")
#define SHEET_CONDUCTOR_SEL__NOT_ON_BEAT FM_STRING("notOnBeat")
#define SHEET_CONDUCTOR_SEL__FROM_PITCH FM_STRING("fromPitch")
#define SHEET_CONDUCTOR_SEL__TO_PITCH FM_STRING("toPitch")
#define SHEET_CONDUCTOR_SEL__PITCH FM_STRING("pitch")
#define SHEET_CONDUCTOR_SEL__INSTRUMENT FM_STRING("instrument")

#define SHEET_CONDUCTOR_SEL__FROM_BEAT FM_STRING("fromBeat")
#define SHEET_CONDUCTOR_SEL__TO_BEAT FM_STRING("toBeat")
#define SHEET_CONDUCTOR_SEL__FROM_BAR FM_STRING("fromBar")
#define SHEET_CONDUCTOR_SEL__TO_BAR FM_STRING("toBar")
#define SHEET_CONDUCTOR_SEL__ON_BAR FM_STRING("onBar")
#define SHEET_CONDUCTOR_SEL__NTH_BAR FM_STRING("nthBar")
#define SHEET_CONDUCTOR_SEL__CHANNEL FM_STRING("channel")
#define SHEET_CONDUCTOR_SEL__EXPRESSION FM_STRING("expression")

// declarartions
#define SHEET_CONDUCTOR_DEC__VELOCITY FM_STRING("velocity")
#define SHEET_CONDUCTOR_DEC__TIME_OFFSET FM_STRING("timeOffset")
#define SHEET_CONDUCTOR_DEC__LENGTH FM_STRING("duration")
#define SHEET_CONDUCTOR_DEC__PITCH FM_STRING("pitch")
