#ifndef CONDUCTOR_NAMES_H
#define CONDUCTOR_NAMES_H

#include <fm/common.hpp>

// selectors
#define SHEET_CONDUCTOR_SEL__FROM_POSITION FM_STRING("fromPosition")
#define SHEET_CONDUCTOR_SEL__TO_POSITION FM_STRING("toPosition")
#define SHEET_CONDUCTOR_SEL__ON_BEAT FM_STRING("onBeat")
#define SHEET_CONDUCTOR_SEL__FROM_PITCH FM_STRING("fromPitch")
#define SHEET_CONDUCTOR_SEL__TO_PITCH FM_STRING("toPitch")
#define SHEET_CONDUCTOR_SEL__PITCH FM_STRING("pitch")
#define SHEET_CONDUCTOR_SEL__INSTRUMENT FM_STRING("instrument")

#define SHEET_CONDUCTOR_SEL__FROM_BEAT FM_STRING("fromBeat")
#define SHEET_CONDUCTOR_SEL__TO_BEAT   FM_STRING("toBeat")
#define SHEET_CONDUCTOR_SEL__FROM_BAR  FM_STRING("fromBar")
#define SHEET_CONDUCTOR_SEL__TO_BAR    FM_STRING("toBar")
#define SHEET_CONDUCTOR_SEL__ON_BAR    FM_STRING("onBar")
#define SHEET_CONDUCTOR_SEL__NTH_BAR   FM_STRING("nthBar")

// declarartions
#define SHEET_CONDUCTOR_DEC__VELOCITY FM_STRING("velocity")
#define SHEET_CONDUCTOR_DEC__TIME_OFFSET FM_STRING("timeOffset")
#define SHEET_CONDUCTOR_DEC__LENGTH FM_STRING("duration")

#endif