#ifndef COMPILER_SPIELANWEISUNGEN_H
#define COMPILER_SPIELANWEISUNGEN_H

#include <fm/common.hpp>
#define SHEET_SPIELANWEISUNG_NORMAL FM_STRING("normal")
#define SHEET_SPIELANWEISUNG_ARPEGGIO FM_STRING("arpeggio")
#endif