#ifndef COMPILER_SPIELANWEISUNGEN_H
#define COMPILER_SPIELANWEISUNGEN_H

#include <com/common.hpp>
#define SHEET_SPIELANWEISUNG_ARPEGGIO FM_STRING("arpeggio")
#define SHEET_SPIELANWEISUNG_VORSCHLAG FM_STRING("vorschlag")
#endif